apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1  # corrected 'replica' to 'replicas'
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:  # added this to match selector
        app: apache
    spec:
      containers:
      - name: apache  # added '-' to define container list
        image: httpd:latest
        ports:
        - containerPort: 80
        resources:  # corrected from 'resource' to 'resources'
          requests:
            cpu: "100m"
            memory: "128Mi"  # corrected 'mi' to 'Mi'
          limits:
            cpu: "200m"
            memory: "256Mi"